=== a047233/tcm25twg04/schema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
    <xsd:element name="filme">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="titulo" type="xsd:string"/>
                <xsd:element name="opinioes">
                    <xsd:complexType>
                        <xsd:sequence>
                            <xsd:element name="critica" maxOccurs="unbounded">
                                <xsd:complexType>
                                    <xsd:sequence>
                                        <xsd:element name="autor" type="xsd:string"/>
                                        <xsd:element name="nota" type="xsd:integer"/>
                                        <xsd:element name="comentario" type="xsd:string"/>
                                    </xsd:sequence>
                                </xsd:complexType>
                            </xsd:element>
                        </xsd:sequence>
                    </xsd:complexType>
                </xsd:element>
                <xsd:element name="curiosidades">
                    <xsd:complexType>
                        <xsd:sequence>
                            <xsd:element name="item" maxOccurs="unbounded">
                                <xsd:complexType>
                                    <xsd:simpleContent>
                                        <xsd:extension base="xsd:string">
                                            <xsd:attribute name="categoria" type="xsd:string"/>
                                        </xsd:extension>
                                    </xsd:simpleContent>
                                </xsd:complexType>
                            </xsd:element>
                        </xsd:sequence>
                    </xsd:complexType>
                </xsd:element>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>
</xsd:schema>

=== a047233/tcm25twg04/dados.xml
<?xml version="1.0" encoding="UTF-8"?>
<filme xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="schema.xsd">
    <titulo>A Substancia</titulo>
    
    <opinioes>
        <critica>
            <autor>Variety</autor>
            <nota>9</nota>
            <comentario>Uma obra-prima visceral de Demi Moore.</comentario>
        </critica>
        <critica>
            <autor>Joao Silva</autor>
            <nota>8</nota>
            <comentario>Visualmente incrivel e perturbador na medida certa.</comentario>
        </critica>
    </opinioes>

    <curiosidades>
        <item categoria="Producao">O filme venceu o premio de Melhor Argumento em Cannes.</item>
        <item categoria="Elenco">Demi Moore considera este um dos papeis mais desafiantes da sua carreira.</item>
        <item categoria="Tecnico">Os efeitos praticos foram preferidos em vez de CGI para maior realismo.</item>
    </curiosidades>
</filme>
